watch_challenge_homepage:
    path:     /
    defaults: { _controller: WatchChallengeBundle:Default:index }
watch_by_slug:
    path:     /watch/{brand}-{model}-{sku}
    defaults: { _controller: WatchChallengeBundle:Watch:getBySlug }
watch_add:
    path:     /watch/create
    defaults: { _controller: WatchChallengeBundle:Watch:create }
watch_update:
    path:     /watch/update
    defaults: { _controller: WatchChallengeBundle:Watch:update }
watch_delete:
    path:     /watch/delete
    defaults: { _controller: WatchChallengeBundle:Watch:delete }
