WatchChallengeBundle\Entity\Brand:
    type: entity
    table: brands
    repositoryClass: WatchChallengeBundle\Repository\BrandRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        updated:
            type: datetime
            nullable: true
        created:
            type: datetime
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
