WatchChallengeBundle\Entity\CaseMaterial:
    type: entity
    table: null
    repositoryClass: WatchChallengeBundle\Repository\CaseMaterialRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            unique: true
        updated:
            type: datetime
            nullable: true
        created:
            type: datetime
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
