WatchChallengeBundle\Entity\Watch:
    type: entity
    table: watches
    repositoryClass: WatchChallengeBundle\Repository\WatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        model:
            type: string
            length: '64'
        caseSite:
            type: integer
            nullable: true
            column: case_site
        bracelet:
            type: string
            length: 255
            nullable: true
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    separator: -
                    style: camel
                    fields:
                        - model
                        - sku
        sku:
            type: string
            length: 255
            nullable: true
        updated:
            type: datetime
            nullable: true
        created:
            type: datetime
    oneToMany:
        watchImages:
            targetEntity: WatchChallengeBundle\Entity\WatchImage
            cascade: ["persist","remove"]
            joinColumn:
                name: id
                referencedColumnName: watch_id
            mappedBy: watch
    manyToOne:
        brand:
            targetEntity: WatchChallengeBundle\Entity\Brand
            joinColumn:
                name: brand_id
                referencedColumnName: id
                nullable: true
        caseMaterial:
            targetEntity: WatchChallengeBundle\Entity\CaseMaterial
            joinColumn:
                name: case_material_id
                referencedColumnName: id
                nullable: true
        condition:
            targetEntity: WatchChallengeBundle\Entity\WatchCondition
            joinColumn:
                name: condition_id
                referencedColumnName: id
                nullable: true
    manyToMany:
        watchFunctions:
            targetEntity: WatchChallengeBundle\Entity\WatchFunction
            joinTable:
                name: crossWatchesWatchFunctions
                joinColumns:
                    watch_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    watch_function_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
