WatchChallengeBundle\Entity\WatchCondition:
    type: entity
    table: watch_conditions
    repositoryClass: WatchChallengeBundle\Repository\WatchConditionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        conditionName:
            type: string
            length: 255
            unique: true
        updated:
            type: datetime
            nullable: true
        created:
            type: datetime
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
