WatchChallengeBundle\Entity\WatchImage:
    type: entity
    table: watch_images
    repositoryClass: WatchChallengeBundle\Repository\WatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255
            unique: true
        updated:
            type: datetime
            nullable: true
        created:
            type: datetime
    manyToOne:
        watch:
            targetEntity: WatchChallengeBundle\Entity\Watch
            inversedBy: watchImages
            nullable: false
    lifecycleCallbacks:
        prePersist: [setCreatedValue]
        preUpdate:  [setUpdatedValue]
