<?php

namespace WatchChallengeBundle\Repository;

/**
 * CaseMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
