<?php

namespace WatchChallengeBundle\Repository;

/**
 * WatchConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
