<?php

namespace WatchChallengeBundle\Repository;

use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * WatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByBrandModelSKU($brand, $model, $sku){
        $query = $this->createQueryBuilder('w');
        $query->innerJoin('w.brand', 'b');
        $query->where('b.name = :brand');
        $query->andWhere('w.model = :model');
        $query->andWhere('w.sku = :sku');
        $query->setParameter('model', $model);
        $query->setParameter('brand', $brand);
        $query->setParameter('sku', $sku);

        return $query->getQuery()->getOneOrNullResult();
    }
}
