<?php

namespace WatchChallengeBundle\Repository;

/**
 * WatchFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
